const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),mode=params.get('mode')==='video'?'video':'robot';
const config=mode==='video'?{title:'脑控视频终端',index:'SYSTEM 02 · VIDEO',src:'./video.html',command:d=>d.video_command,classValue:d=>d.predicted_index}:{title:'机械臂抓取终端',index:'SYSTEM 01 · GRASP',src:'./robot.html',command:d=>d.robot_target,classValue:d=>d.predicted_index+1};
const colors=['#00a98f','#3978f6','#8e6df2','#e8a33c','#ef5d68','#63b84c'];let cursor=0,timer=null,busy=false,replayRecords=[],waveFrame=null,waveSeries=null,waveStartedAt=0,waveLastFrame=0;
if(mode==='robot')$('speed').innerHTML='<option value="20000" selected>20秒</option><option value="25000">25秒</option><option value="30000">30秒</option>';
const wait=ms=>new Promise(r=>setTimeout(r,ms));function stamp(){return new Date().toLocaleTimeString('zh-CN',{hour12:false})}function log(message,tone=''){const box=$('unityLog'),p=document.createElement('p');p.innerHTML=`<time>${stamp()}</time><span class="${tone}">${message}</span>`;box.appendChild(p);box.scrollTop=box.scrollHeight;while(box.children.length>18)box.firstElementChild.remove()}function setStage(name){let reached=false;document.querySelectorAll('.flow-node').forEach(n=>{const hit=n.dataset.stage===name;if(hit)reached=true;n.classList.toggle('active',hit);n.classList.toggle('done',!hit&&!reached)})}
function nextReplay(){const subject=$('subject').value,candidates=replayRecords.filter(d=>subject==='all'||d.subject===subject);if(!candidates.length)throw new Error(`没有被试 ${subject} 的回放数据`);const position=cursor%candidates.length,d=candidates[position];cursor=(position+1)%candidates.length;return d}
async function init(){document.title=`NeuroGrasp · ${config.title}`;$('pageTitle').textContent=config.title;$('terminalTitle').textContent=config.title;$('terminalIndex').textContent=config.index;$('unityFrame').src=config.src;$(`${mode}Nav`).classList.add('active');if(mode==='robot')$('robotGuide').hidden=false;const [m,records]=await Promise.all([fetch('./data/meta.json').then(r=>{if(!r.ok)throw new Error('meta.json 加载失败');return r.json()}),fetch('./data/trials.json').then(r=>{if(!r.ok)throw new Error('trials.json 加载失败');return r.json()})]);replayRecords=records;const s=m.summary;$('model').textContent='FBAR-Net 脑电解码';$('modelVersion').textContent=m.model;$('totalTrials').textContent=s.n;$('accuracy').textContent=(s.accuracy*100).toFixed(1);$('latency').textContent=s.mean_latency_ms.toFixed(1);$('acceptedRate').textContent=(s.accepted_rate*100).toFixed(1);$('subject').innerHTML='<option value="all">全部8名被试</option>'+m.subjects.map(x=>`<option value="${x}">${x}</option>`).join('');$('subject').value=m.subjects.includes('S6(zy)')?'S6(zy)':m.subjects[0];drawIdle();setInterval(()=>$('clock').textContent=new Date().toLocaleString('zh-CN',{hour12:false}),1000)}
async function step(){if(busy)return;busy=true;$('step').disabled=true;try{setStage('eeg');log('读取固定测试集中的 1 秒 EEG 窗口','muted');const d=nextReplay();$('signalSubject').textContent=`${d.subject} · trial ${d.source_trial}`;$('signalInfo').textContent=`P3 · PZ · P4 · O1 · OZ · O2 · ${d.sample_rate} Hz`;startWave(d.waveform);if(mode==='robot'){$('unityFrame').contentWindow.presentStimulus(d.true_index+1);log(`原 ssvep 范式：10/12/14 Hz 三刺激块同时闪烁，注视目标 ${d.true_frequency_hz} Hz`,'ok');await wait(1000)}else await wait(250);setStage('quality');log('输入校验通过：6 ch × 1000 samples','ok');await wait(mode==='robot'?3000:280);setStage('decode');log(`FBAR-Net：${d.predicted_frequency_hz} Hz，confidence=${d.confidence.toFixed(3)}`,'ok');await wait(280);setStage('gate');log(d.accepted?'置信度门控：ACCEPTED':'置信度门控：REJECTED',d.accepted?'ok':'warn');render(d);await wait(280);setStage('dispatch');if(d.accepted){$('unityFrame').contentWindow.selectTarget(config.classValue(d),d.confidence);log(`${d.predicted_frequency_hz} Hz → ${config.command(d)}`,'ok')}else log('低置信度，当前终端保持不变','warn')}catch(e){log('回放错误：'+e.message,'error')}finally{busy=false;$('step').disabled=false}}
function render(d){$('frequency').textContent=d.predicted_frequency_hz;$('confidence').textContent=(d.confidence*100).toFixed(1)+'%';$('confidenceBar').style.width=(d.confidence*100)+'%';$('activeCommand').textContent=config.command(d);$('decision').textContent=d.accepted?(d.correct?'通过 · 正确':'通过 · 误分类'):'拒绝';$('decision').style.color=d.accepted?(d.correct?'#20d2b3':'#e8a33c'):'#ef5d68';$('trialLatency').textContent=d.latency_ms.toFixed(1)+' ms'}
function drawWave(series,offset=0){const c=$('wave'),x=c.getContext('2d'),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.strokeStyle='#dbe4e1';x.lineWidth=1;for(let i=1;i<6;i++){x.beginPath();x.moveTo(0,i*h/6);x.lineTo(w,i*h/6);x.stroke()}series.forEach((a,ch)=>{const base=(ch+.5)*h/6;x.strokeStyle=colors[ch];x.lineWidth=1.4;x.beginPath();for(let i=0;i<a.length;i++){const v=a[(i+offset)%a.length],px=i/(a.length-1)*w,py=base-v*h/27;i?x.lineTo(px,py):x.moveTo(px,py)}x.stroke()})}
function waveTick(now){if(!waveSeries){waveFrame=null;return}if(now-waveLastFrame>=40){const offset=Math.floor((now-waveStartedAt)*.045)%waveSeries[0].length;drawWave(waveSeries,offset);waveLastFrame=now}waveFrame=requestAnimationFrame(waveTick)}
function startWave(series){waveSeries=series;waveStartedAt=performance.now();waveLastFrame=0;if(!waveFrame)waveFrame=requestAnimationFrame(waveTick)}
function stopWave(){waveSeries=null;if(waveFrame)cancelAnimationFrame(waveFrame);waveFrame=null}
function drawIdle(){stopWave();drawWave(Array.from({length:6},(_,ch)=>Array.from({length:180},(_,i)=>Math.sin(i*.12+ch)*.05)))}
function stop(){if(timer)clearInterval(timer);timer=null;$('play').classList.remove('running');$('play').innerHTML='<i></i>开始伪在线'}function play(){stop();step();timer=setInterval(step,+$('speed').value);$('play').classList.add('running');$('play').innerHTML='<i></i>暂停回放'}function reset(){stop();cursor=0;setStage('eeg');$('unityLog').innerHTML='';log('系统复位，等待 EEG 回放','muted');$('frequency').textContent='—';$('confidence').textContent='—';$('confidenceBar').style.width='0';$('activeCommand').textContent='等待回放';$('decision').textContent='—';$('trialLatency').textContent='—';drawIdle()}
$('step').onclick=step;$('play').onclick=()=>timer?stop():play();$('reset').onclick=reset;$('subject').onchange=reset;$('speed').onchange=()=>{if(timer)play()};window.addEventListener('message',e=>{if(e.data?.type==='unity-ready'&&e.data.view===mode){$('unityState').textContent='READY';$('unityState').classList.add('ready');log('Unity WebGL 已连接','ok')}if(e.data?.type==='unity-robot-event')log(e.data.payload.event==='grasp_complete'?'抓取与放置完成':'机械臂事件：'+e.data.payload.event,'ok')});if(mode==='robot'){const frame=$('unityFrame');frame.style.pointerEvents='none';frame.title='Unity 画面（页面可直接滚动）';if('IntersectionObserver'in window)new IntersectionObserver(([entry])=>frame.contentWindow?.setUnityPaused?.(!entry.isIntersecting),{threshold:0}).observe(frame)}init().catch(e=>log('初始化失败：'+e.message,'error'));
